# Generated by Django 5.1 on 2024-08-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='folder_thumbnails/'),
        ),
        migrations.AddField(
            model_name='folder',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='file_thumbnails/'),
        ),
    ]
