# Generated by Django 5.1 on 2024-08-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_file_thumbnail_folder_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='thumbnail',
        ),
    ]
