# Generated by Django 5.1 on 2024-08-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_file_thumbnail_folder_thumbnail_delete_driveitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
