# Generated by Django 5.1 on 2024-08-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_alter_folder_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/files/'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/folders/'),
        ),
    ]
