# Generated by Django 5.1 on 2024-08-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0009_alter_file_thumbnail_alter_folder_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
