# Generated by Django 5.1 on 2024-08-27 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0010_alter_file_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_spam',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_starred',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_trash',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='is_starred',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='is_trash',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='drive.folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drive.file'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
