# Generated by Django 5.1 on 2024-08-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0011_rename_created_at_file_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
