# Generated by Django 5.1 on 2024-08-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0012_file_is_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
