# Generated by Django 5.1 on 2024-08-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0014_file_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
