# Generated by Django 5.1 on 2024-08-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0015_folder_is_trash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_spam',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_trash',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='is_trash',
        ),
    ]
