# Generated by Django 5.1 on 2024-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0016_remove_file_is_spam_remove_file_is_trash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
