# Generated by Django 5.1 on 2024-08-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0019_folder_is_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
