# Generated by Django 4.2 on 2024-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drive", "0020_folder_updated_at_folder_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="url",
            field=models.URLField(default="http://127.0.0.1.8000"),
        ),
    ]
